### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by wku** [nixel2007/docker-selenium-side-runner#1]
does not work, you have thoughts with what it can be connected?
You can also upload to the repository an example of a file  .side that works.

- data for testing .side
https://i.imgur.com/T4KQ5LE.png

- console output
https://i.imgur.com/DQZQeZX.png

etc
selenium-side-runner_1  | FAIL ./Default Suite.test.js (17.87s)
selenium-side-runner_1  |   Default Suite
selenium-side-runner_1  |     ✕ Untitled (16324ms)
selenium-side-runner_1  | 
selenium-side-runner_1  |   ● Default Suite › Untitled
selenium-side-runner_1  | 
selenium-side-runner_1  |     TimeoutError: Waiting for element to be located By(css selector, input.lsb)
selenium-side-runner_1  |     Wait timed out after 15001ms

thank

**Comment by nixel2007** [comment]
Hello. Could you provide your `side` file as text here so i can check it on my end?

**Comment by wku** [comment]
I figured out
it was big and complicated .side  and it fell while processing

I understand that now the library selenium-side-runner  does not fully support what works in the version of the browser extension.

thank
