### ISSUE TITLE
Error on docker-compose up

### ISSUE THREAD

**Issue by crossanpdx** [nixel2007/docker-selenium-side-runner#2]
error:   runner is too old to run the project file, upgrade the runner using: `npm i -g selenium-side-runner@latest`

**Comment by nixel2007** [comment]
Hello. Did you build your own image, or use one from docker hub?

**Comment by crossanpdx** [comment]
Pulled your project as is and followed the quick start.

**Comment by nixel2007** [comment]
I've rebuilded the latest tag. Could you try to re-pull?
