### ISSUE TITLE
Did you think about using the official selenium image for chrome driver / firefox?

### ISSUE THREAD

**Issue by amenk** [nixel2007/docker-selenium-side-runner#5]
I am using

      chromedriver:
        image: selenium/standalone-chrome-debug

in the compose file.

but have problems:

 FAIL  ./DefaultSuite.test.js
  ● Test suite failed to run

    UnsupportedOperationError: newSession: <!DOCTYPE html>

Do you have an idea? What is the reason to not use the official chrome driver?

**Comment by amenk** [comment]
it's working well when specifying this entry-point
 /wd/hub was missing :)

selenium-side-runner -s http://chromedriver:4444/wd/hub --timeout 30000 --output-directory /root/out /sides/*.side

Will publish in the fork imi-digital

**Comment by nixel2007** [comment]
glad to hear you've resolved your issue :) if you want to edit something in docker-compose/dockerfile in this repo - feel free to send a pr
